name: Checkout
description: ''
inputs:
  with:
    submodules: 
      required: false
      default: true
    fetch-depth:
      required: false
      default: 1
    ref:
      required: false
      default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        ref: ${{ inputs.ref }}

    - name: Fetch test data
      if: ${{ inputs.submodules }}
      shell: bash
      run: |
        # This avoids "fatal: detected dubious ownership in repository"
        git config --system --add safe.directory "$GITHUB_WORKSPACE"

        # We disable submodule updates in .gitmodules so Cargo doesn't check them out
        # when this repo is used as a git dependency, but we need that data for tests. 
        # "--checkout" acquires it for us normally.
        git -c protocol.version=2 submodule update --init --checkout --force --depth=${{ inputs.fetch-depth }}